service: aws-lambda-old-resource-detector

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:ListFunctions"
        - "lambda:ListTags"
        - "cloudformation:DescribeStacks"
        - "cloudformation:ListStackResources"
      Resource: "*"

  environment:
    DURATION_DAYS: 7

functions:
  detector:
    handler: handler.detector
    memorySize: 128
    timeout: 30

